# Generated by Django 3.0.5 on 2020-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('aim', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('feet', models.FloatField()),
                ('inches', models.FloatField()),
                ('c', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
